# Generated by Django 3.2 on 2021-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1997-11-25'),
            preserve_default=False,
        ),
    ]
